version: "3.9"
services:
    api:
        image: heinrian/hs-distributed-systems-lab-todo-backend-spring-boot:latest
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todoapp
        ports:
            - "8090:8090"
        networks:
            - backend
        depends_on:
            - db

    db:
        image: postgres:14
        environment:
            - POSTGRES_DB=todoapp
            - POSTGRES_USER=todoapp
            - POSTGRES_PASSWORD=example
        networks:
            - backend
        volumes:
            - dbdata:/var/lib/postgresql/data

volumes:
    dbdata:

networks:
    backend:

